find_path(ZeroMQ_INCLUDE_DIR NAMES zmq.h PATHS ${CONAN_INCLUDE_DIRS_ZMQ} NO_CMAKE_FIND_ROOT_PATH)
find_library(ZeroMQ_LIBRARY NAMES ${CONAN_LIBS_ZMQ} PATHS ${CONAN_LIB_DIRS_ZMQ} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** ZeroMQ ALREADY FOUND BY CONAN!")
SET(ZeroMQ_FOUND TRUE)
MESSAGE("** FOUND ZeroMQ:  ${ZeroMQ_LIBRARY}")
MESSAGE("** FOUND ZeroMQ INCLUDE:  ${ZeroMQ_INCLUDE_DIR}")

set(ZeroMQ_INCLUDE_DIRS ${ZeroMQ_INCLUDE_DIR})
set(ZeroMQ_LIBRARIES ${ZeroMQ_LIBRARY})

mark_as_advanced(ZeroMQ_LIBRARY ZeroMQ_INCLUDE_DIR)

set(ZeroMQ_MAJOR_VERSION "4")
set(ZeroMQ_MINOR_VERSION "2")
set(ZeroMQ_PATCH_VERSION "2")
set(ZeroMQ_VER "${ZeroMQ_MAJOR_VERSION}.${ZeroMQ_MINOR_VERSION}.${ZeroMQ_PATCH_VERSION}")
set(ZeroMQ_VERSION ${ZeroMQ_VER})

add_library(libzmq INTERFACE IMPORTED)
set_property(TARGET libzmq PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${ZeroMQ_INCLUDE_DIRS})
set_property(TARGET libzmq PROPERTY INTERFACE_LINK_LIBRARIES ${ZeroMQ_LIBRARIES})

add_library(libzmq-static INTERFACE IMPORTED)
set_property(TARGET libzmq-static PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${ZeroMQ_INCLUDE_DIRS})
set_property(TARGET libzmq-static PROPERTY INTERFACE_LINK_LIBRARIES ${ZeroMQ_LIBRARIES})
